#!/usr/bin/env python3
"""Take the think-cell bookkeeping out of a PowerPoint-authored deck.

`test-kit/modern-chart.pptx` is a RECORDING — a sunburst chart written by real
PowerPoint, kept so the engine is checked against somebody else's bytes rather
than against a fixture its own author wrote. It is not regenerated by CI and
should not be edited by hand.

One thing was removed from it before it was committed, and this script is that
removal, written down so the file's provenance stays checkable. The deck was
authored on a machine with think-cell installed, and think-cell stamps every
deck it touches with a bookkeeping OLE object: `p:oleObj progId=
"TCLayout.ActiveDocument.1"` on the slide, ~38 KB of its own binary in
`ppt/embeddings/`, a rendered EMF for the fallback branch, and two tag parts
holding `THINKCELLSHAPEDONOTDELETE` — one on the slide, one on the slide master.
This repository is public, and redistributing another vendor's binary was not
the point of the file.

Nothing the engine touches is affected: the chart, its embedded workbook, the
slide's text and the chart's own `mc:AlternateContent` are untouched, and the
strip is parts and relationships only — no XML the merge reads is rewritten.

What IS lost is one piece of coverage the original had, and it is worth knowing:
the slide carried a SECOND `mc:AlternateContent` that was not a chart, which is
exactly what `replaceModernChartFallbacks` matching on the graphicData URI rather
than on the `Requires` token protects. `test/chart-modern.test.ts` covers that
case against a fixture instead.

`docProps/app.xml` still names "think-cell Slide" under Embedded OLE Servers.
That is a stale metadata string PowerPoint wrote, not think-cell's data, and it
is left alone: rewriting the parallel vectors in that part to hide it would be
editing the recording for appearance's sake.

    python3 test-kit/strip-thinkcell.py sunburst.pptx test-kit/modern-chart.pptx
"""
import re
import shutil
import sys
import zipfile

# Parts that are think-cell's and nothing else's. `image1.emf` is the picture in
# the OLE object's own fallback branch, reachable only from the block that goes.
DROP_PARTS = {
    "ppt/embeddings/oleObject1.bin",
    "ppt/embeddings/oleObject2.bin",
    "ppt/media/image1.emf",
    "ppt/tags/tag1.xml",
    "ppt/tags/tag2.xml",
}

# Relationship TARGETS to drop wherever they are referenced from. Matched on the
# target rather than on a relationship id, because the ids differ per part and a
# hard-coded id would silently stop matching if the deck were ever re-recorded.
DROP_TARGETS = ("../embeddings/oleObject", "../media/image1.emf", "../tags/tag")

# The OLE object is not loose on the slide: it sits inside a hidden
# `<p:graphicFrame>` named "think-cell data - do not delete", and taking only the
# `<mc:AlternateContent>` out leaves that frame behind holding an empty
# `<a:graphicData>` — a shape naming think-cell, with nothing in it. The whole
# frame goes.
#
# Non-greedy, and safe here because a graphic frame does not nest: the chart's
# own frame is inside its `mc:AlternateContent`, and neither contains another.
FRAME = re.compile(r"<p:graphicFrame>.*?</p:graphicFrame>", re.S)
CUSTDATA = re.compile(r"<p:custDataLst>.*?</p:custDataLst>", re.S)

# What marks a frame as think-cell's. The progId is on the slide's copy, the
# name on both it and the slide master's.
THINKCELL = ("TCLayout.ActiveDocument", 'name="think-cell data - do not delete"')
RELATIONSHIP = re.compile(r"<Relationship\b[^>]*/>")
CONTENT_TYPE = re.compile(r"<(?:Override|Default)\b[^>]*/>")


def strip_slide(xml: str) -> str:
    """Drop the think-cell frame and the part's reference to its tag part."""
    # Only a frame carrying one of think-cell's own marks. The chart is a graphic
    # frame too, and it stays.
    kept = FRAME.sub(
        lambda m: "" if any(t in m.group(0) for t in THINKCELL) else m.group(0), xml
    )
    return CUSTDATA.sub("", kept)


def strip_rels(xml: str) -> str:
    return RELATIONSHIP.sub(
        lambda m: "" if any(t in (m.group(0)) for t in DROP_TARGETS) else m.group(0), xml
    )


def strip_content_types(xml: str) -> str:
    # The tag overrides name parts that are gone. `bin` and `emf` are Defaults
    # for extensions no remaining part uses; a Default naming an extension that
    # does not occur is legal, but leaving them would say the package still holds
    # an OLE object.
    def keep(m: str) -> bool:
        if 'PartName="/ppt/tags/' in m:
            return False
        return not any(f'Extension="{e}"' in m for e in ("bin", "emf"))

    return CONTENT_TYPE.sub(lambda m: m.group(0) if keep(m.group(0)) else "", xml)


def main(source: str, target: str) -> None:
    with zipfile.ZipFile(source) as zin:
        names = [n for n in zin.namelist() if n not in DROP_PARTS]
        with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as zout:
            for name in names:
                data = zin.read(name)
                if name in ("ppt/slides/slide1.xml", "ppt/slideMasters/slideMaster1.xml"):
                    data = strip_slide(data.decode("utf8")).encode("utf8")
                elif name.endswith(".rels"):
                    data = strip_rels(data.decode("utf8")).encode("utf8")
                elif name == "[Content_Types].xml":
                    data = strip_content_types(data.decode("utf8")).encode("utf8")
                zout.writestr(name, data)
    print(f"wrote {target}")


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
