#!/usr/bin/env node
/**
 * Build the host probe: two fixture decks and a snippet that inserts them.
 *
 * The decks are built HERE, by the engine, and embedded in the snippet as
 * base64. The snippet then needs no libraries, does no zip work in a hostile
 * runtime, and tests exactly the question rather than the code that prepares
 * it. It also means the probe can be pasted into Script Lab with nothing else
 * installed.
 *
 * Two arms, because one cannot answer:
 *   fresh      two slides with DIFFERENT creation ids, which is what the
 *              engine produces;
 *   collision  the same two slides sharing ONE creation id, which is the
 *              shape office-js#6105 reports failing.
 * Asking only the first cannot separate "the bug is absent here" from "this
 * host refuses every insert".
 */
import { writeFileSync } from "node:fs";
import { Pkg } from "../dist-lib/core/pptx/pkg.js";
import { cloneSlide } from "../dist-lib/core/pptx/clone.js";
import { writeSlideTags, TAG_RUN } from "../dist-lib/core/pptx/tags.js";
import { makeDeck } from "./probe-fixture.mjs";

const RUN_TAG = "probe-run";

/** A deck of two slides whose creation ids differ, tagged in the package. */
async function freshDeck() {
  const pkg = await Pkg.open(await makeDeck());
  const copy = await cloneSlide(pkg, "ppt/slides/slide1.xml", { creationId: () => 424242 });
  await writeSlideTags(pkg, "ppt/slides/slide1.xml", [[TAG_RUN, RUN_TAG]]);
  await writeSlideTags(pkg, copy, [[TAG_RUN, RUN_TAG]]);
  return pkg.toBase64();
}

/** The same two slides, deliberately sharing one creation id. */
async function collisionDeck() {
  const pkg = await Pkg.open(await makeDeck());
  await cloneSlide(pkg, "ppt/slides/slide1.xml", { creationId: () => 111111 });
  // Force the template to the copy's id, so the deck holds the collision.
  const { setCreationId } = await import("../dist-lib/core/pptx/clone.js");
  await setCreationId(pkg, "ppt/slides/slide1.xml", 111111);
  return pkg.toBase64();
}

const fresh = await freshDeck();
const collision = await collisionDeck();

const snippet = `/*
 * SSF Merge — host probe
 *
 * Paste this whole file into a blank Script Lab snippet in PowerPoint and press
 * Run. It appends slides to the end of the current deck, asks five questions,
 * removes what it added, and prints a JSON block.
 *
 * COPY THAT JSON BACK. It is the answer sheet, and nothing in the add-in should
 * be built on a guess about any of these.
 *
 * Generated by scripts/build-probe.mjs — do not edit here.
 */

const FRESH_DECK = "${fresh}";
const COLLISION_DECK = "${collision}";
const TAG = "SSF_MERGE_RUN";

/** Every call is bounded. On this host a stall is death, not slowness. */
function withTimeout<T>(p: Promise<T>, ms: number, what: string): Promise<T> {
  return Promise.race([
    p,
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error(\`gave up waiting for: \${what}\`)), ms)),
  ]);
}

async function slideCount(): Promise<number> {
  return PowerPoint.run(async (context) => {
    const count = context.presentation.slides.getCount();
    await context.sync();
    return count.value;
  });
}

/**
 * The bytes of the presentation this is running in.
 *
 * The control arm for question one. A deck PowerPoint saved seconds ago cannot
 * be a malformed package, so a host that refuses it is refusing insertion
 * itself rather than judging our writer.
 */
function currentDeckBase64(): Promise<string> {
  return new Promise((resolve, reject) => {
    Office.context.document.getFileAsync(Office.FileType.Compressed, { sliceSize: 4194304 }, (res) => {
      if (res.status !== Office.AsyncResultStatus.Succeeded) {
        reject(new Error(res.error ? res.error.message : "getFileAsync would not open the file"));
        return;
      }
      const file = res.value;
      const chunks: string[] = [];
      const next = (i: number): void => {
        if (i >= file.sliceCount) {
          file.closeAsync();
          resolve(btoa(chunks.join("")));
          return;
        }
        file.getSliceAsync(i, (sl) => {
          if (sl.status !== Office.AsyncResultStatus.Succeeded) {
            file.closeAsync();
            reject(new Error(sl.error ? sl.error.message : "getSliceAsync refused a slice"));
            return;
          }
          const bytes = sl.value.data as number[];
          // Chunked, because apply() on a whole slice blows the argument limit.
          let s = "";
          for (let j = 0; j < bytes.length; j += 0x8000) {
            s += String.fromCharCode.apply(null, bytes.slice(j, j + 0x8000));
          }
          chunks.push(s);
          next(i + 1);
        });
      };
      next(0);
    });
  });
}

async function insertDeck(
  base64: string,
  formatting: PowerPoint.InsertSlideFormatting | "KeepSourceFormatting" | "UseDestinationTheme" = "KeepSourceFormatting",
): Promise<{ before: number; after: number; error?: string }> {
  const before = await slideCount();
  let error: string | undefined;
  try {
    await withTimeout(
      PowerPoint.run(async (context) => {
        // Without a target the host inserts at the FRONT, which would put these
        // slides ahead of the user's own title slide.
        const last = context.presentation.slides.getItemAt(before - 1);
        last.load("id");
        await context.sync();
        // A bad targetSlideId throws SlideNotFound, not InvalidArgument, so the
        // options are not what a rejection here is about.
        context.presentation.insertSlidesFromBase64(base64, { formatting, targetSlideId: last.id });
        await context.sync();
      }),
      30000,
      "inserting a deck",
    );
  } catch (e) {
    error = e instanceof Error ? e.message : String(e);
  }
  return { before, after: await slideCount(), error };
}

/** Question 2: does a tag written into the FILE read back through the API? */
async function readTagBack(index: number): Promise<{ value?: string; error?: string }> {
  try {
    return await withTimeout(
      PowerPoint.run(async (context) => {
        const slide = context.presentation.slides.getItemAt(index);
        const tag = slide.tags.getItemOrNullObject(TAG);
        tag.load("value,isNullObject");
        await context.sync();
        return tag.isNullObject ? {} : { value: tag.value };
      }),
      15000,
      "reading a tag written into the package",
    );
  } catch (e) {
    return { error: e instanceof Error ? e.message : String(e) };
  }
}

/** Questions 3 and 4: substring writes, formatting and offsets. */
async function substringProbe(): Promise<Record<string, unknown>> {
  // Four separate calls used to share one catch, so a throw named none of them
  // and a sheet reported "InvalidArgument" about an unknown statement. The step
  // is written before each call, so the error carries the call that raised it.
  let step = "starting";
  try {
    return await withTimeout(
      PowerPoint.run(async (context) => {
        const slides = context.presentation.slides;
        const count = slides.getCount();
        await context.sync();
        const slide = slides.getItemAt(count.value - 1);

        step = "adding a text box";
        const shape = slide.shapes.addTextBox("Hello NAME here and AAA-BBB", {
          left: 40,
          top: 40,
          width: 400,
          height: 60,
        });
        await context.sync();

        // Style just the placeholder, so a flattened run is visible afterwards.
        step = "styling a substring of a shape added a sync ago";
        shape.textFrame.textRange.getSubstring(6, 4).font.bold = true;
        await context.sync();

        step = "reading the text back";
        const before = shape.textFrame.textRange;
        before.load("text");
        await context.sync();
        const textBefore = before.text;

        // Q3: one targeted write.
        step = "writing one substring";
        shape.textFrame.textRange.getSubstring(6, 4).text = "Ada";
        await context.sync();

        const mid = shape.textFrame.textRange;
        mid.load("text");
        const styled = shape.textFrame.textRange.getSubstring(6, 3).font;
        styled.load("bold");
        await context.sync();

        // Q4: two writes queued in ONE batch, at offsets taken from the text as
        // it stands now. If they are independent the later one lands where the
        // caller meant; if the first shifts the second, it does not.
        const text = mid.text;
        const a = text.indexOf("AAA");
        const b = text.indexOf("BBB");
        step = "queuing two substring writes in one batch";
        shape.textFrame.textRange.getSubstring(a, 3).text = "1";
        shape.textFrame.textRange.getSubstring(b, 3).text = "2";
        await context.sync();

        const end = shape.textFrame.textRange;
        end.load("text");
        await context.sync();

        step = "deleting the probe text box";
        const name = shape.name;
        shape.delete();
        await context.sync();

        return {
          textBefore,
          textAfterOne: text,
          boldAfter: styled.bold,
          twoWrites: { offsets: [a, b], after: end.text },
          shape: name,
        };
      }),
      30000,
      "probing substring writes",
    );
  } catch (e) {
    return { error: e instanceof Error ? e.message : String(e), failedAt: step };
  }
}

/** Positional, never by id: a slide this run added does not resolve by id here. */
async function sweep(deckAtStart: number, added: number): Promise<string> {
  const deckNow = await slideCount();
  const grew = deckNow - deckAtStart;
  const count = Math.min(added, grew);
  const from = deckNow - count;
  if (count <= 0 || from < deckAtStart) return \`left everything alone (start \${deckAtStart}, now \${deckNow})\`;
  try {
    await PowerPoint.run(async (context) => {
      // Highest index first, so removing one cannot shift another.
      for (let i = from + count - 1; i >= from; i--) context.presentation.slides.getItemAt(i).delete();
      await context.sync();
    });
    return \`removed \${count} slide(s) from index \${from}\`;
  } catch (e) {
    return \`could not clean up: \${e instanceof Error ? e.message : String(e)}\`;
  }
}

async function main() {
  const deckAtStart = await slideCount();
  const answers: Record<string, unknown> = {
    probe: "ssf-merge",
    takenAt: new Date().toISOString(),
    platform: Office.context.platform,
    host: Office.context.diagnostics?.version ?? "unknown",
    requirementSets: ["1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10"].filter((v) =>
      Office.context.requirements.isSetSupported("PowerPointApi", v),
    ),
    deckAtStart,
  };

  // The control runs FIRST, while the deck is still only the user's own, so it
  // inserts exactly what was there and nothing this run has added.
  try {
    const own = await withTimeout(currentDeckBase64(), 30000, "reading this presentation's own bytes");
    answers.insertSelf = await insertDeck(own);
  } catch (e) {
    answers.insertSelf = { before: -1, after: -1, error: e instanceof Error ? e.message : String(e) };
  }

  answers.insertFresh = await insertDeck(FRESH_DECK);
  answers.tagReadBack = await readTagBack((await slideCount()) - 1);
  // Same package, the other formatting mode. KeepSourceFormatting has to import
  // the source theme and UseDestinationTheme does not, so the pair separates a
  // theme this host will not read from a package it will not read.
  answers.insertFreshDestTheme = await insertDeck(FRESH_DECK, "UseDestinationTheme");
  answers.insertCollision = await insertDeck(COLLISION_DECK);
  answers.substring = await substringProbe();

  const deckNow = await slideCount();
  answers.sweep = await sweep(deckAtStart, deckNow - deckAtStart);
  answers.deckAtEnd = await slideCount();

  console.log("=== SSF MERGE ANSWER SHEET — copy everything between the markers ===");
  console.log(JSON.stringify(answers, null, 2));
  console.log("=== END ===");
}

main().catch((e) => console.error("the probe itself failed:", e));
`;

writeFileSync("probe/probe-snippet.ts", snippet);
console.log(
  `probe/probe-snippet.ts written (${snippet.length} bytes, decks ${fresh.length} + ${collision.length} base64 chars)`,
);
