#!/usr/bin/env node
/**
 * Build the host probe: two fixture decks and a snippet that inserts them.
 *
 * The decks are built HERE, by the engine, and embedded in the snippet as
 * base64. The snippet then needs no libraries, does no zip work in a hostile
 * runtime, and tests exactly the question rather than the code that prepares
 * it. It also means the probe can be pasted into Script Lab with nothing else
 * installed.
 *
 * Two arms, because one cannot answer:
 *   fresh      two slides with DIFFERENT creation ids, which is what the
 *              engine produces;
 *   collision  the same two slides sharing ONE creation id, which is the
 *              shape office-js#6105 reports failing.
 * Asking only the first cannot separate "the bug is absent here" from "this
 * host refuses every insert".
 */
import { writeFileSync } from "node:fs";
import { Pkg } from "../dist-lib/core/pptx/pkg.js";
import { cloneSlide } from "../dist-lib/core/pptx/clone.js";
import { writeSlideTags, TAG_RUN } from "../dist-lib/core/pptx/tags.js";
import { Q3, Q4 } from "../dist-lib/host/verdicts.js";
import { makeDeck } from "./probe-fixture.mjs";

const RUN_TAG = "probe-run";

/** A deck of two slides whose creation ids differ, tagged in the package. */
async function freshDeck() {
  const pkg = await Pkg.open(await makeDeck());
  const copy = await cloneSlide(pkg, "ppt/slides/slide1.xml", { creationId: () => 424242 });
  await writeSlideTags(pkg, "ppt/slides/slide1.xml", [[TAG_RUN, RUN_TAG]]);
  await writeSlideTags(pkg, copy, [[TAG_RUN, RUN_TAG]]);
  return pkg.toBase64();
}

/** The same two slides, deliberately sharing one creation id. */
async function collisionDeck() {
  const pkg = await Pkg.open(await makeDeck());
  await cloneSlide(pkg, "ppt/slides/slide1.xml", { creationId: () => 111111 });
  // Force the template to the copy's id, so the deck holds the collision.
  const { setCreationId } = await import("../dist-lib/core/pptx/clone.js");
  await setCreationId(pkg, "ppt/slides/slide1.xml", 111111);
  return pkg.toBase64();
}

const fresh = await freshDeck();
const collision = await collisionDeck();

const snippet = `/*
 * SSF Merge — host probe
 *
 * Paste this whole file into a blank Script Lab snippet in PowerPoint and press
 * Run. It appends slides to the end of the current deck, asks seven questions,
 * removes what it added, and prints a JSON block.
 *
 * COPY THAT JSON BACK. It is the answer sheet, and nothing in the add-in should
 * be built on a guess about any of these.
 *
 * Generated by scripts/build-probe.mjs — do not edit here.
 */

const FRESH_DECK = "${fresh}";
const COLLISION_DECK = "${collision}";
const TAG = "SSF_MERGE_RUN";

/** Every call is bounded. On this host a stall is death, not slowness. */
function withTimeout<T>(p: Promise<T>, ms: number, what: string): Promise<T> {
  return Promise.race([
    p,
    new Promise<T>((_, reject) => setTimeout(() => reject(new Error(\`gave up waiting for: \${what}\`)), ms)),
  ]);
}

async function slideCount(): Promise<number> {
  return PowerPoint.run(async (context) => {
    const count = context.presentation.slides.getCount();
    await context.sync();
    return count.value;
  });
}

/**
 * The bytes of the presentation this is running in.
 *
 * The control arm for question one. A deck PowerPoint saved seconds ago cannot
 * be a malformed package, so a host that refuses it is refusing insertion
 * itself rather than judging our writer.
 */
function currentDeckBase64(): Promise<string> {
  return new Promise((resolve, reject) => {
    Office.context.document.getFileAsync(Office.FileType.Compressed, { sliceSize: 4194304 }, (res) => {
      if (res.status !== Office.AsyncResultStatus.Succeeded) {
        reject(new Error(res.error ? res.error.message : "getFileAsync would not open the file"));
        return;
      }
      const file = res.value;
      const chunks: string[] = [];
      const next = (i: number): void => {
        if (i >= file.sliceCount) {
          file.closeAsync();
          resolve(btoa(chunks.join("")));
          return;
        }
        file.getSliceAsync(i, (sl) => {
          if (sl.status !== Office.AsyncResultStatus.Succeeded) {
            file.closeAsync();
            reject(new Error(sl.error ? sl.error.message : "getSliceAsync refused a slice"));
            return;
          }
          const bytes = sl.value.data as number[];
          // Chunked, because apply() on a whole slice blows the argument limit.
          let s = "";
          for (let j = 0; j < bytes.length; j += 0x8000) {
            s += String.fromCharCode.apply(null, bytes.slice(j, j + 0x8000));
          }
          chunks.push(s);
          next(i + 1);
        });
      };
      next(0);
    });
  });
}

async function insertDeck(
  base64: string,
  formatting: PowerPoint.InsertSlideFormatting | "KeepSourceFormatting" | "UseDestinationTheme" = "KeepSourceFormatting",
): Promise<{ before: number; after: number; error?: string }> {
  const before = await slideCount();
  let error: string | undefined;
  try {
    await withTimeout(
      PowerPoint.run(async (context) => {
        // Without a target the host inserts at the FRONT, which would put these
        // slides ahead of the user's own title slide.
        const last = context.presentation.slides.getItemAt(before - 1);
        last.load("id");
        await context.sync();
        // A bad targetSlideId throws SlideNotFound, not InvalidArgument, so the
        // options are not what a rejection here is about.
        context.presentation.insertSlidesFromBase64(base64, { formatting, targetSlideId: last.id });
        await context.sync();
      }),
      // 30s was not enough once: the third sheet timed out on an insert whose
      // deck delta showed both slides had landed. A budget that expires on a
      // call that worked produces a false refusal, which is the more expensive
      // direction here.
      60000,
      "inserting a deck",
    );
  } catch (e) {
    error = e instanceof Error ? e.message : String(e);
  }
  return { before, after: await slideCount(), error };
}

/** Question 2: does a tag written into the FILE read back through the API? */
async function readTagBack(index: number): Promise<{ value?: string; error?: string }> {
  try {
    return await withTimeout(
      PowerPoint.run(async (context) => {
        const slide = context.presentation.slides.getItemAt(index);
        const tag = slide.tags.getItemOrNullObject(TAG);
        tag.load("value,isNullObject");
        await context.sync();
        return tag.isNullObject ? {} : { value: tag.value };
      }),
      15000,
      "reading a tag written into the package",
    );
  } catch (e) {
    return { error: e instanceof Error ? e.message : String(e) };
  }
}

/**
 * Questions 3 and 4, each in ONE batch.
 *
 * The first sheet that got this far answered
 * \`5010: InvalidParam passed to GetItem(id)\` at "styling a substring of a shape
 * added a sync ago". Office.js rewrites a created shape's object path to
 * \`shapes.getItem(id)\` once it has been through a sync, and this host refuses
 * that id — the shape exists, it just will not be named again. So nothing here
 * touches a shape proxy across a \`context.sync()\`: every write is queued in the
 * same batch that created the shape, and the only sync is the one that reads
 * the answers back.
 *
 * That is also the shape a real merge has, which makes it the more honest test:
 * a run queues its replacements and syncs once.
 *
 * Two shapes rather than one, because the two questions want different text. A
 * single shape would make question four's expected answers depend on question
 * three's write, and the point of question four is that those two models must
 * be told apart cleanly.
 */
const Q3_TEXT = "${Q3.text}";
// "AAA-BBB": write five characters over AAA, then three over what WAS BBB.
// Independent offsets give "XXXXX-2"; a second write that saw the first one's
// result is three characters to the left and gives "XXXX2BB". Neither model
// runs off the end of the string, so a throw here means something else.
const Q4_TEXT = "${Q4.text}";

async function substringProbe(deckGrew: boolean): Promise<Record<string, unknown>> {
  // The shapes land on the LAST slide, which is one this run inserted — so the
  // positional sweep takes them away with it and nothing has to delete a shape
  // through a proxy this host will not name. When no insert landed, that slide
  // is the user's own, and the question is skipped rather than drawn on it.
  if (!deckGrew) {
    return { skipped: "no slide of the probe's own to draw on, so this was not asked" };
  }
  let step = "starting";
  try {
    return await withTimeout(
      PowerPoint.run(async (context) => {
        const slides = context.presentation.slides;
        const count = slides.getCount();
        await context.sync();
        const slide = slides.getItemAt(count.value - 1);

        step = "question 3: create, style and write in one batch";
        const three = slide.shapes.addTextBox(Q3_TEXT, { left: 40, top: 40, width: 400, height: 60 });
        // Style just the placeholder, so a flattened run is visible afterwards.
        three.textFrame.textRange.getSubstring(6, 4).font.bold = true;
        three.textFrame.textRange.getSubstring(6, 4).text = "Ada";
        const threeText = three.textFrame.textRange;
        threeText.load("text");
        const threeFont = three.textFrame.textRange.getSubstring(6, 3).font;
        threeFont.load("bold");

        step = "question 4: create and queue two writes in one batch";
        const four = slide.shapes.addTextBox(Q4_TEXT, { left: 40, top: 120, width: 400, height: 60 });
        four.textFrame.textRange.getSubstring(0, 3).text = "XXXXX";
        four.textFrame.textRange.getSubstring(4, 3).text = "2";
        const fourText = four.textFrame.textRange;
        fourText.load("text");

        step = "reading both back";
        await context.sync();

        return {
          textBefore: Q3_TEXT,
          textAfterOne: threeText.text,
          boldAfter: threeFont.bold,
          twoWrites: { offsets: [0, 4], after: fourText.text },
        };
      }),
      30000,
      "probing substring writes",
    );
  } catch (e) {
    return { error: e instanceof Error ? e.message : String(e), failedAt: step };
  }
}

/** Positional, never by id: a slide this run added does not resolve by id here. */
async function sweep(deckAtStart: number, added: number): Promise<string> {
  const deckNow = await slideCount();
  const grew = deckNow - deckAtStart;
  const count = Math.min(added, grew);
  const from = deckNow - count;
  if (count <= 0 || from < deckAtStart) return \`left everything alone (start \${deckAtStart}, now \${deckNow})\`;
  try {
    await PowerPoint.run(async (context) => {
      // Highest index first, so removing one cannot shift another.
      for (let i = from + count - 1; i >= from; i--) context.presentation.slides.getItemAt(i).delete();
      await context.sync();
    });
    return \`removed \${count} slide(s) from index \${from}\`;
  } catch (e) {
    return \`could not clean up: \${e instanceof Error ? e.message : String(e)}\`;
  }
}

/**
 * Does \`slides.load("items/id")\` answer as many slides as \`getCount()\` says?
 *
 * office-js#4272 reports a load of more than ~50 items answering SHORT on the
 * web, and a sibling add-in pages every collection read at 20 because of it.
 * This add-in loads the WHOLE deck's ids twice — once to pick the template
 * block's ids, once to turn a selection into slide numbers — and a mail-merge
 * template deck is exactly the kind that gets large.
 *
 * Three facts, none inferable from the others:
 *
 * - \`count\` against \`items\`: whether the read is short at all, at THIS size.
 * - \`prefixOk\`: whether a short read is the first n IN DECK ORDER. If it is,
 *   the damage is bounded — a block inside the prefix is right and one past it
 *   is refused. If it is not, \`deckIds.indexOf(id)\` returns the wrong slide
 *   NUMBER, silently, and the merge clones slides nobody chose. Checked against
 *   \`getItemAt\`, which is a different code path and not subject to a
 *   collection load's ceiling.
 * - \`empty\`: whether the read comes back with nothing after a sync that
 *   SUCCEEDED — office-js#6363, and the sibling project's central failure.
 *
 * \`deckSize\` is reported because a nine-slide deck cannot answer the >50
 * question and must not look as though it did.
 */
async function deckReadProbe(): Promise<Record<string, unknown>> {
  const out: Record<string, unknown> = {};
  try {
    await withTimeout(
      PowerPoint.run(async (context) => {
        const slides = context.presentation.slides;
        const count = slides.getCount();
        slides.load("items/id");
        await context.sync();

        const loaded = slides.items.map((s) => s.id);
        out.deckSize = count.value;
        out.items = loaded.length;
        out.short = loaded.length < count.value;
        out.empty = loaded.length === 0;
        out.canAnswerFiftyQuestion = count.value > 50;

        // The same ids by POSITION, which is how a paged reader would take
        // them. Bounded to what the collection returned plus a few past it, so
        // a large deck does not turn this into a hundred syncs.
        const upTo = Math.min(count.value, Math.max(loaded.length, 1) + 3);
        const handles = [];
        for (let i = 0; i < upTo; i++) {
          const slide = slides.getItemAt(i);
          slide.load("id");
          handles.push(slide);
        }
        await context.sync();
        const positional = handles.map((h) => h.id);
        out.byPosition = positional.length;
        // The load's answer is the first n of the deck, in order.
        out.prefixOk = loaded.every((id, i) => id === positional[i]);
      }),
      20000,
      "reading the deck's slide ids",
    );
  } catch (e) {
    out.error = e instanceof Error ? e.message : String(e);
  }
  return out;
}

/**
 * The part names in a package, read from its zip central directory.
 *
 * Names only — never content. A part list is structure, and this sheet is
 * written to be copied out of a console and pasted into an issue, where the
 * merged values would be somebody's salary review.
 *
 * The central directory rather than a scan for local headers: the four-byte
 * signature occurs inside compressed data often enough that a scan invents
 * parts, and an instrument that invents findings is worse than none. The
 * end-of-central-directory record says where the real list starts and how many
 * entries it has, so the walk is exact.
 *
 * Works on the binary string \`atob\` returns rather than a Uint8Array: a deck
 * is tens of megabytes and the copy buys nothing here.
 */
function partNamesOf(base64: string): string[] {
  const s = atob(base64);
  const u16 = (i: number): number => s.charCodeAt(i) | (s.charCodeAt(i + 1) << 8);
  const u32 = (i: number): number => u16(i) + u16(i + 2) * 0x10000;
  // The EOCD is last, after a comment of at most 65535 bytes.
  let eocd = -1;
  for (let i = s.length - 22; i >= 0 && i >= s.length - 22 - 65535; i--) {
    if (s.charCodeAt(i) === 0x50 && s.charCodeAt(i + 1) === 0x4b && s.charCodeAt(i + 2) === 0x05 && s.charCodeAt(i + 3) === 0x06) {
      eocd = i;
      break;
    }
  }
  if (eocd < 0) throw new Error("no end-of-central-directory record — this is not a zip");
  const count = u16(eocd + 10);
  let at = u32(eocd + 16);
  const names: string[] = [];
  for (let n = 0; n < count; n++) {
    if (s.charCodeAt(at) !== 0x50 || s.charCodeAt(at + 1) !== 0x4b || s.charCodeAt(at + 2) !== 0x01 || s.charCodeAt(at + 3) !== 0x02) {
      throw new Error("central directory entry " + n + " is not where the header said");
    }
    const nameLen = u16(at + 28);
    names.push(s.substr(at + 46, nameLen));
    at += 46 + nameLen + u16(at + 30) + u16(at + 32);
  }
  return names;
}

/**
 * Does \`exportAsBase64Presentation\` drop parts the file route keeps?
 *
 * office-js#6867 reports \`Slide.exportAsBase64\` omitting modern comments and
 * \`ppt/authors.xml\`. A sibling project triaged it as no exposure and was right
 * to: it calls that API for a PICTURE of a slide. This add-in calls the
 * presentation-level export to read the TEMPLATE IT THEN CLONES, so a part the
 * export drops is a part every merged slide is missing — silently, in a file
 * that opens cleanly. Nobody has checked whether the presentation-level call
 * behaves like the slide-level one.
 *
 * THE CONTROL IS THE POINT. \`getFileAsync\` returns the package unfiltered, so
 * it says what the deck actually holds. Without it, an export with no
 * \`authors.xml\` is indistinguishable from a deck that never had one — and this
 * project has already recorded a sheet that reported a metadata scheme broken
 * on the strength of a read that fell on the wrong slide.
 *
 * Both arms cover the SAME slides, every id in the deck, or the export would
 * legitimately lack the parts belonging to the slides it was not asked for.
 */
async function exportPartsProbe(): Promise<Record<string, unknown>> {
  const out: Record<string, unknown> = {};
  if (!Office.context.requirements.isSetSupported("PowerPointApi", "1.10")) {
    // Not a "no". The call does not exist here, so the question was never put,
    // and reporting that as "it drops nothing" would be an answer this run did
    // not earn.
    out.supported = false;
    return out;
  }
  out.supported = true;
  try {
    const source = partNamesOf(await withTimeout(currentDeckBase64(), 60000, "reading the deck's own bytes"));
    const exported = partNamesOf(
      await withTimeout(
        PowerPoint.run(async (context) => {
          const slides = context.presentation.slides;
          slides.load("items/id");
          await context.sync();
          const bytes = slides.exportAsBase64Presentation(slides.items.map((s) => s.id));
          await context.sync();
          return bytes.value;
        }),
        60000,
        "exporting every slide in the deck",
      ),
    );
    const inExport = new Set(exported);
    const inSource = new Set(source);
    const comments = (names: string[]): number =>
      names.filter((n) => n.indexOf("ppt/comments/") === 0 || n.indexOf("ppt/modernComments/") === 0).length;

    out.sourceParts = source.length;
    out.exportParts = exported.length;
    // Capped: a deck with two hundred dropped media parts must not push the
    // one part this question is about off the end of the list.
    out.missing = source.filter((n) => !inExport.has(n)).slice(0, 40);
    out.addedByExport = exported.filter((n) => !inSource.has(n)).slice(0, 40);
    out.sourceHasAuthors = inSource.has("ppt/authors.xml");
    out.exportHasAuthors = inExport.has("ppt/authors.xml");
    out.sourceComments = comments(source);
    out.exportComments = comments(exported);
  } catch (e) {
    out.error = e instanceof Error ? e.message : String(e);
  }
  return out;
}

/**
 * Does an insert land while a SHAPE is selected?
 *
 * office-js#2775 reports \`addTextBox\` deleting the selected shape on the web,
 * and #3698 reports a PICTURE refusing to insert while one is selected. This
 * add-in inserts SLIDES, which is neither — but nobody has established that,
 * and the preview step now inserts at a moment when the user may well have
 * something selected. A sibling add-in drops the selection before every draw;
 * doing the same here would mean CALLING \`setSelectedShapes\`, which is the one
 * call in this family with a measured history of wedging the host. So the
 * question is asked before any code is written for it.
 *
 * Read-only about the selection: it never selects anything, it only reports
 * what was already selected and whether the insert worked anyway.
 */
async function insertWhileSelectedProbe(): Promise<Record<string, unknown>> {
  const out: Record<string, unknown> = {};
  try {
    out.shapesSelected = await withTimeout(
      PowerPoint.run(async (context) => {
        const shapes = context.presentation.getSelectedShapes();
        shapes.load("items/id");
        await context.sync();
        return shapes.items.length;
      }),
      15000,
      "reading the selected shapes",
    );
  } catch (e) {
    // 1.5, and the floor is 1.2 — an older host simply cannot say.
    out.shapesSelected = -1;
    out.selectionReadError = e instanceof Error ? e.message : String(e);
  }
  const before = await slideCount();
  out.insert = await insertDeck(FRESH_DECK);
  out.landed = (await slideCount()) - before;
  return out;
}

async function main() {
  const deckAtStart = await slideCount();
  const answers: Record<string, unknown> = {
    probe: "ssf-merge",
    takenAt: new Date().toISOString(),
    platform: Office.context.platform,
    host: Office.context.diagnostics?.version ?? "unknown",
    requirementSets: ["1.2", "1.3", "1.4", "1.5", "1.6", "1.7", "1.8", "1.9", "1.10"].filter((v) =>
      Office.context.requirements.isSetSupported("PowerPointApi", v),
    ),
    deckAtStart,
  };

  // The control runs FIRST, while the deck is still only the user's own, so it
  // inserts exactly what was there and nothing this run has added.
  try {
    const own = await withTimeout(currentDeckBase64(), 30000, "reading this presentation's own bytes");
    answers.insertSelf = await insertDeck(own);
  } catch (e) {
    answers.insertSelf = { before: -1, after: -1, error: e instanceof Error ? e.message : String(e) };
  }

  answers.insertFresh = await insertDeck(FRESH_DECK);
  answers.tagReadBack = await readTagBack((await slideCount()) - 1);
  // Same package, the other formatting mode. KeepSourceFormatting has to import
  // the source theme and UseDestinationTheme does not, so the pair separates a
  // theme this host will not read from a package it will not read.
  answers.insertFreshDestTheme = await insertDeck(FRESH_DECK, "UseDestinationTheme");
  answers.insertCollision = await insertDeck(COLLISION_DECK);
  // Only draws if this run has a slide of its own to draw on.
  answers.substring = await substringProbe((await slideCount()) > deckAtStart);
  // How the deck's own id list behaves — the read this add-in does twice and
  // pages nowhere. See deckReadProbe.
  answers.deckRead = await deckReadProbe();
  // Whether an insert cares that a shape is selected. Asked, never worked
  // around: the workaround would be setSelectedShapes, which is the call with
  // the measured wedging history.
  answers.insertWhileSelected = await insertWhileSelectedProbe();
  // Whether the export this add-in reads its template through keeps every part
  // the file route does. Asked LAST of the reads, because both arms walk the
  // whole deck and the earlier arms have added to it — which costs time and
  // changes nothing, since the comparison is between two reads of the same
  // deck at the same moment.
  answers.exportParts = await exportPartsProbe();

  const deckNow = await slideCount();
  answers.sweep = await sweep(deckAtStart, deckNow - deckAtStart);
  answers.deckAtEnd = await slideCount();

  console.log("=== SSF MERGE ANSWER SHEET — copy everything between the markers ===");
  console.log(JSON.stringify(answers, null, 2));
  console.log("=== END ===");
}

main().catch((e) => console.error("the probe itself failed:", e));
`;

writeFileSync("probe/probe-snippet.ts", snippet);
console.log(
  `probe/probe-snippet.ts written (${snippet.length} bytes, decks ${fresh.length} + ${collision.length} base64 chars)`,
);
